package com.sd.Admin.pojo;

public class sd_activity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.activity_id
     *
     * @mbg.generated
     */
    private String activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.activity_title
     *
     * @mbg.generated
     */
    private String activityTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.activity_content
     *
     * @mbg.generated
     */
    private String activityContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.activity_time
     *
     * @mbg.generated
     */
    private String activityTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.activity_creater
     *
     * @mbg.generated
     */
    private String activityCreater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.activity_state
     *
     * @mbg.generated
     */
    private Integer activityState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.activity_data
     *
     * @mbg.generated
     */
    private String activityData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_activity.activity_place
     *
     * @mbg.generated
     */
    private String activityPlace;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.Id
     *
     * @return the value of sd_activity.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.Id
     *
     * @param id the value for sd_activity.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.activity_id
     *
     * @return the value of sd_activity.activity_id
     *
     * @mbg.generated
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.activity_id
     *
     * @param activityId the value for sd_activity.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.activity_title
     *
     * @return the value of sd_activity.activity_title
     *
     * @mbg.generated
     */
    public String getActivityTitle() {
        return activityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.activity_title
     *
     * @param activityTitle the value for sd_activity.activity_title
     *
     * @mbg.generated
     */
    public void setActivityTitle(String activityTitle) {
        this.activityTitle = activityTitle == null ? null : activityTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.activity_content
     *
     * @return the value of sd_activity.activity_content
     *
     * @mbg.generated
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.activity_content
     *
     * @param activityContent the value for sd_activity.activity_content
     *
     * @mbg.generated
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.activity_time
     *
     * @return the value of sd_activity.activity_time
     *
     * @mbg.generated
     */
    public String getActivityTime() {
        return activityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.activity_time
     *
     * @param activityTime the value for sd_activity.activity_time
     *
     * @mbg.generated
     */
    public void setActivityTime(String activityTime) {
        this.activityTime = activityTime == null ? null : activityTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.activity_creater
     *
     * @return the value of sd_activity.activity_creater
     *
     * @mbg.generated
     */
    public String getActivityCreater() {
        return activityCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.activity_creater
     *
     * @param activityCreater the value for sd_activity.activity_creater
     *
     * @mbg.generated
     */
    public void setActivityCreater(String activityCreater) {
        this.activityCreater = activityCreater == null ? null : activityCreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.student_id
     *
     * @return the value of sd_activity.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.student_id
     *
     * @param studentId the value for sd_activity.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.activity_state
     *
     * @return the value of sd_activity.activity_state
     *
     * @mbg.generated
     */
    public Integer getActivityState() {
        return activityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.activity_state
     *
     * @param activityState the value for sd_activity.activity_state
     *
     * @mbg.generated
     */
    public void setActivityState(Integer activityState) {
        this.activityState = activityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.activity_data
     *
     * @return the value of sd_activity.activity_data
     *
     * @mbg.generated
     */
    public String getActivityData() {
        return activityData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.activity_data
     *
     * @param activityData the value for sd_activity.activity_data
     *
     * @mbg.generated
     */
    public void setActivityData(String activityData) {
        this.activityData = activityData == null ? null : activityData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_activity.activity_place
     *
     * @return the value of sd_activity.activity_place
     *
     * @mbg.generated
     */
    public String getActivityPlace() {
        return activityPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_activity.activity_place
     *
     * @param activityPlace the value for sd_activity.activity_place
     *
     * @mbg.generated
     */
    public void setActivityPlace(String activityPlace) {
        this.activityPlace = activityPlace == null ? null : activityPlace.trim();
    }
}