package com.sd.Admin.pojo;

import java.util.ArrayList;
import java.util.List;

public class sd_checkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public sd_checkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNull() {
            addCriterion("check_id is null");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNotNull() {
            addCriterion("check_id is not null");
            return (Criteria) this;
        }

        public Criteria andCheckIdEqualTo(String value) {
            addCriterion("check_id =", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotEqualTo(String value) {
            addCriterion("check_id <>", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThan(String value) {
            addCriterion("check_id >", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThanOrEqualTo(String value) {
            addCriterion("check_id >=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThan(String value) {
            addCriterion("check_id <", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThanOrEqualTo(String value) {
            addCriterion("check_id <=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLike(String value) {
            addCriterion("check_id like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotLike(String value) {
            addCriterion("check_id not like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdIn(List<String> values) {
            addCriterion("check_id in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotIn(List<String> values) {
            addCriterion("check_id not in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdBetween(String value1, String value2) {
            addCriterion("check_id between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotBetween(String value1, String value2) {
            addCriterion("check_id not between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckGradeIsNull() {
            addCriterion("check_grade is null");
            return (Criteria) this;
        }

        public Criteria andCheckGradeIsNotNull() {
            addCriterion("check_grade is not null");
            return (Criteria) this;
        }

        public Criteria andCheckGradeEqualTo(Integer value) {
            addCriterion("check_grade =", value, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeNotEqualTo(Integer value) {
            addCriterion("check_grade <>", value, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeGreaterThan(Integer value) {
            addCriterion("check_grade >", value, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_grade >=", value, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeLessThan(Integer value) {
            addCriterion("check_grade <", value, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeLessThanOrEqualTo(Integer value) {
            addCriterion("check_grade <=", value, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeIn(List<Integer> values) {
            addCriterion("check_grade in", values, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeNotIn(List<Integer> values) {
            addCriterion("check_grade not in", values, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeBetween(Integer value1, Integer value2) {
            addCriterion("check_grade between", value1, value2, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("check_grade not between", value1, value2, "checkGrade");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIsNull() {
            addCriterion("check_time is null");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIsNotNull() {
            addCriterion("check_time is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTimeEqualTo(String value) {
            addCriterion("check_time =", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotEqualTo(String value) {
            addCriterion("check_time <>", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeGreaterThan(String value) {
            addCriterion("check_time >", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeGreaterThanOrEqualTo(String value) {
            addCriterion("check_time >=", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeLessThan(String value) {
            addCriterion("check_time <", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeLessThanOrEqualTo(String value) {
            addCriterion("check_time <=", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeLike(String value) {
            addCriterion("check_time like", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotLike(String value) {
            addCriterion("check_time not like", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIn(List<String> values) {
            addCriterion("check_time in", values, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotIn(List<String> values) {
            addCriterion("check_time not in", values, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeBetween(String value1, String value2) {
            addCriterion("check_time between", value1, value2, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotBetween(String value1, String value2) {
            addCriterion("check_time not between", value1, value2, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIsNull() {
            addCriterion("check_type is null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIsNotNull() {
            addCriterion("check_type is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeEqualTo(Integer value) {
            addCriterion("check_type =", value, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNotEqualTo(Integer value) {
            addCriterion("check_type <>", value, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeGreaterThan(Integer value) {
            addCriterion("check_type >", value, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_type >=", value, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLessThan(Integer value) {
            addCriterion("check_type <", value, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLessThanOrEqualTo(Integer value) {
            addCriterion("check_type <=", value, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIn(List<Integer> values) {
            addCriterion("check_type in", values, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNotIn(List<Integer> values) {
            addCriterion("check_type not in", values, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeBetween(Integer value1, Integer value2) {
            addCriterion("check_type between", value1, value2, "checkType");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("check_type not between", value1, value2, "checkType");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryIsNull() {
            addCriterion("check_mdormitory is null");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryIsNotNull() {
            addCriterion("check_mdormitory is not null");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryEqualTo(Integer value) {
            addCriterion("check_mdormitory =", value, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryNotEqualTo(Integer value) {
            addCriterion("check_mdormitory <>", value, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryGreaterThan(Integer value) {
            addCriterion("check_mdormitory >", value, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_mdormitory >=", value, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryLessThan(Integer value) {
            addCriterion("check_mdormitory <", value, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryLessThanOrEqualTo(Integer value) {
            addCriterion("check_mdormitory <=", value, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryIn(List<Integer> values) {
            addCriterion("check_mdormitory in", values, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryNotIn(List<Integer> values) {
            addCriterion("check_mdormitory not in", values, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryBetween(Integer value1, Integer value2) {
            addCriterion("check_mdormitory between", value1, value2, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMdormitoryNotBetween(Integer value1, Integer value2) {
            addCriterion("check_mdormitory not between", value1, value2, "checkMdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryIsNull() {
            addCriterion("check_ndormitory is null");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryIsNotNull() {
            addCriterion("check_ndormitory is not null");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryEqualTo(Integer value) {
            addCriterion("check_ndormitory =", value, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryNotEqualTo(Integer value) {
            addCriterion("check_ndormitory <>", value, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryGreaterThan(Integer value) {
            addCriterion("check_ndormitory >", value, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_ndormitory >=", value, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryLessThan(Integer value) {
            addCriterion("check_ndormitory <", value, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryLessThanOrEqualTo(Integer value) {
            addCriterion("check_ndormitory <=", value, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryIn(List<Integer> values) {
            addCriterion("check_ndormitory in", values, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryNotIn(List<Integer> values) {
            addCriterion("check_ndormitory not in", values, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryBetween(Integer value1, Integer value2) {
            addCriterion("check_ndormitory between", value1, value2, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckNdormitoryNotBetween(Integer value1, Integer value2) {
            addCriterion("check_ndormitory not between", value1, value2, "checkNdormitory");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonIsNull() {
            addCriterion("check_mlesson is null");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonIsNotNull() {
            addCriterion("check_mlesson is not null");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonEqualTo(Integer value) {
            addCriterion("check_mlesson =", value, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonNotEqualTo(Integer value) {
            addCriterion("check_mlesson <>", value, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonGreaterThan(Integer value) {
            addCriterion("check_mlesson >", value, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_mlesson >=", value, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonLessThan(Integer value) {
            addCriterion("check_mlesson <", value, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonLessThanOrEqualTo(Integer value) {
            addCriterion("check_mlesson <=", value, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonIn(List<Integer> values) {
            addCriterion("check_mlesson in", values, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonNotIn(List<Integer> values) {
            addCriterion("check_mlesson not in", values, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonBetween(Integer value1, Integer value2) {
            addCriterion("check_mlesson between", value1, value2, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMlessonNotBetween(Integer value1, Integer value2) {
            addCriterion("check_mlesson not between", value1, value2, "checkMlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonIsNull() {
            addCriterion("check_zlesson is null");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonIsNotNull() {
            addCriterion("check_zlesson is not null");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonEqualTo(Integer value) {
            addCriterion("check_zlesson =", value, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonNotEqualTo(Integer value) {
            addCriterion("check_zlesson <>", value, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonGreaterThan(Integer value) {
            addCriterion("check_zlesson >", value, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_zlesson >=", value, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonLessThan(Integer value) {
            addCriterion("check_zlesson <", value, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonLessThanOrEqualTo(Integer value) {
            addCriterion("check_zlesson <=", value, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonIn(List<Integer> values) {
            addCriterion("check_zlesson in", values, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonNotIn(List<Integer> values) {
            addCriterion("check_zlesson not in", values, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonBetween(Integer value1, Integer value2) {
            addCriterion("check_zlesson between", value1, value2, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckZlessonNotBetween(Integer value1, Integer value2) {
            addCriterion("check_zlesson not between", value1, value2, "checkZlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonIsNull() {
            addCriterion("check_nlesson is null");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonIsNotNull() {
            addCriterion("check_nlesson is not null");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonEqualTo(Integer value) {
            addCriterion("check_nlesson =", value, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonNotEqualTo(Integer value) {
            addCriterion("check_nlesson <>", value, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonGreaterThan(Integer value) {
            addCriterion("check_nlesson >", value, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_nlesson >=", value, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonLessThan(Integer value) {
            addCriterion("check_nlesson <", value, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonLessThanOrEqualTo(Integer value) {
            addCriterion("check_nlesson <=", value, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonIn(List<Integer> values) {
            addCriterion("check_nlesson in", values, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonNotIn(List<Integer> values) {
            addCriterion("check_nlesson not in", values, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonBetween(Integer value1, Integer value2) {
            addCriterion("check_nlesson between", value1, value2, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckNlessonNotBetween(Integer value1, Integer value2) {
            addCriterion("check_nlesson not between", value1, value2, "checkNlesson");
            return (Criteria) this;
        }

        public Criteria andCheckMajorIsNull() {
            addCriterion("check_major is null");
            return (Criteria) this;
        }

        public Criteria andCheckMajorIsNotNull() {
            addCriterion("check_major is not null");
            return (Criteria) this;
        }

        public Criteria andCheckMajorEqualTo(String value) {
            addCriterion("check_major =", value, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorNotEqualTo(String value) {
            addCriterion("check_major <>", value, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorGreaterThan(String value) {
            addCriterion("check_major >", value, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorGreaterThanOrEqualTo(String value) {
            addCriterion("check_major >=", value, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorLessThan(String value) {
            addCriterion("check_major <", value, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorLessThanOrEqualTo(String value) {
            addCriterion("check_major <=", value, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorLike(String value) {
            addCriterion("check_major like", value, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorNotLike(String value) {
            addCriterion("check_major not like", value, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorIn(List<String> values) {
            addCriterion("check_major in", values, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorNotIn(List<String> values) {
            addCriterion("check_major not in", values, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorBetween(String value1, String value2) {
            addCriterion("check_major between", value1, value2, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andCheckMajorNotBetween(String value1, String value2) {
            addCriterion("check_major not between", value1, value2, "checkMajor");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_name is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_name =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_name <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_name >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_name >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_name <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_name <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_name like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_name not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("class_name in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("class_name not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_name between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_name not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_check
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}