package com.sd.Admin.pojo;

public class sd_class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_class.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_class.class_id
     *
     * @mbg.generated
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_class.class_rank
     *
     * @mbg.generated
     */
    private Integer classRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_class.class_major
     *
     * @mbg.generated
     */
    private String classMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_class.class_grade
     *
     * @mbg.generated
     */
    private Integer classGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_class.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_class.Id
     *
     * @return the value of sd_class.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_class.Id
     *
     * @param id the value for sd_class.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_class.class_id
     *
     * @return the value of sd_class.class_id
     *
     * @mbg.generated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_class.class_id
     *
     * @param classId the value for sd_class.class_id
     *
     * @mbg.generated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_class.class_rank
     *
     * @return the value of sd_class.class_rank
     *
     * @mbg.generated
     */
    public Integer getClassRank() {
        return classRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_class.class_rank
     *
     * @param classRank the value for sd_class.class_rank
     *
     * @mbg.generated
     */
    public void setClassRank(Integer classRank) {
        this.classRank = classRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_class.class_major
     *
     * @return the value of sd_class.class_major
     *
     * @mbg.generated
     */
    public String getClassMajor() {
        return classMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_class.class_major
     *
     * @param classMajor the value for sd_class.class_major
     *
     * @mbg.generated
     */
    public void setClassMajor(String classMajor) {
        this.classMajor = classMajor == null ? null : classMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_class.class_grade
     *
     * @return the value of sd_class.class_grade
     *
     * @mbg.generated
     */
    public Integer getClassGrade() {
        return classGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_class.class_grade
     *
     * @param classGrade the value for sd_class.class_grade
     *
     * @mbg.generated
     */
    public void setClassGrade(Integer classGrade) {
        this.classGrade = classGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_class.student_id
     *
     * @return the value of sd_class.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_class.student_id
     *
     * @param studentId the value for sd_class.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }
}