package com.sd.Admin.pojo;

public class sd_check {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_id
     *
     * @mbg.generated
     */
    private String checkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_grade
     *
     * @mbg.generated
     */
    private Integer checkGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_time
     *
     * @mbg.generated
     */
    private String checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_type
     *
     * @mbg.generated
     */
    private Integer checkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_mdormitory
     *
     * @mbg.generated
     */
    private Integer checkMdormitory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_ndormitory
     *
     * @mbg.generated
     */
    private Integer checkNdormitory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_mlesson
     *
     * @mbg.generated
     */
    private Integer checkMlesson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_zlesson
     *
     * @mbg.generated
     */
    private Integer checkZlesson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_nlesson
     *
     * @mbg.generated
     */
    private Integer checkNlesson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.check_major
     *
     * @mbg.generated
     */
    private String checkMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_check.student_name
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.Id
     *
     * @return the value of sd_check.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.Id
     *
     * @param id the value for sd_check.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_id
     *
     * @return the value of sd_check.check_id
     *
     * @mbg.generated
     */
    public String getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_id
     *
     * @param checkId the value for sd_check.check_id
     *
     * @mbg.generated
     */
    public void setCheckId(String checkId) {
        this.checkId = checkId == null ? null : checkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_grade
     *
     * @return the value of sd_check.check_grade
     *
     * @mbg.generated
     */
    public Integer getCheckGrade() {
        return checkGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_grade
     *
     * @param checkGrade the value for sd_check.check_grade
     *
     * @mbg.generated
     */
    public void setCheckGrade(Integer checkGrade) {
        this.checkGrade = checkGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_time
     *
     * @return the value of sd_check.check_time
     *
     * @mbg.generated
     */
    public String getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_time
     *
     * @param checkTime the value for sd_check.check_time
     *
     * @mbg.generated
     */
    public void setCheckTime(String checkTime) {
        this.checkTime = checkTime == null ? null : checkTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_type
     *
     * @return the value of sd_check.check_type
     *
     * @mbg.generated
     */
    public Integer getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_type
     *
     * @param checkType the value for sd_check.check_type
     *
     * @mbg.generated
     */
    public void setCheckType(Integer checkType) {
        this.checkType = checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.student_id
     *
     * @return the value of sd_check.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.student_id
     *
     * @param studentId the value for sd_check.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_mdormitory
     *
     * @return the value of sd_check.check_mdormitory
     *
     * @mbg.generated
     */
    public Integer getCheckMdormitory() {
        return checkMdormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_mdormitory
     *
     * @param checkMdormitory the value for sd_check.check_mdormitory
     *
     * @mbg.generated
     */
    public void setCheckMdormitory(Integer checkMdormitory) {
        this.checkMdormitory = checkMdormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_ndormitory
     *
     * @return the value of sd_check.check_ndormitory
     *
     * @mbg.generated
     */
    public Integer getCheckNdormitory() {
        return checkNdormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_ndormitory
     *
     * @param checkNdormitory the value for sd_check.check_ndormitory
     *
     * @mbg.generated
     */
    public void setCheckNdormitory(Integer checkNdormitory) {
        this.checkNdormitory = checkNdormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_mlesson
     *
     * @return the value of sd_check.check_mlesson
     *
     * @mbg.generated
     */
    public Integer getCheckMlesson() {
        return checkMlesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_mlesson
     *
     * @param checkMlesson the value for sd_check.check_mlesson
     *
     * @mbg.generated
     */
    public void setCheckMlesson(Integer checkMlesson) {
        this.checkMlesson = checkMlesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_zlesson
     *
     * @return the value of sd_check.check_zlesson
     *
     * @mbg.generated
     */
    public Integer getCheckZlesson() {
        return checkZlesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_zlesson
     *
     * @param checkZlesson the value for sd_check.check_zlesson
     *
     * @mbg.generated
     */
    public void setCheckZlesson(Integer checkZlesson) {
        this.checkZlesson = checkZlesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_nlesson
     *
     * @return the value of sd_check.check_nlesson
     *
     * @mbg.generated
     */
    public Integer getCheckNlesson() {
        return checkNlesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_nlesson
     *
     * @param checkNlesson the value for sd_check.check_nlesson
     *
     * @mbg.generated
     */
    public void setCheckNlesson(Integer checkNlesson) {
        this.checkNlesson = checkNlesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.check_major
     *
     * @return the value of sd_check.check_major
     *
     * @mbg.generated
     */
    public String getCheckMajor() {
        return checkMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.check_major
     *
     * @param checkMajor the value for sd_check.check_major
     *
     * @mbg.generated
     */
    public void setCheckMajor(String checkMajor) {
        this.checkMajor = checkMajor == null ? null : checkMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.class_name
     *
     * @return the value of sd_check.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.class_name
     *
     * @param className the value for sd_check.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_check.student_name
     *
     * @return the value of sd_check.student_name
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_check.student_name
     *
     * @param studentName the value for sd_check.student_name
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }
}