package com.sd.Admin.pojo;

import java.util.ArrayList;
import java.util.List;

public class sd_punishExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public sd_punishExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPunishIdIsNull() {
            addCriterion("punish_id is null");
            return (Criteria) this;
        }

        public Criteria andPunishIdIsNotNull() {
            addCriterion("punish_id is not null");
            return (Criteria) this;
        }

        public Criteria andPunishIdEqualTo(String value) {
            addCriterion("punish_id =", value, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdNotEqualTo(String value) {
            addCriterion("punish_id <>", value, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdGreaterThan(String value) {
            addCriterion("punish_id >", value, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdGreaterThanOrEqualTo(String value) {
            addCriterion("punish_id >=", value, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdLessThan(String value) {
            addCriterion("punish_id <", value, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdLessThanOrEqualTo(String value) {
            addCriterion("punish_id <=", value, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdLike(String value) {
            addCriterion("punish_id like", value, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdNotLike(String value) {
            addCriterion("punish_id not like", value, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdIn(List<String> values) {
            addCriterion("punish_id in", values, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdNotIn(List<String> values) {
            addCriterion("punish_id not in", values, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdBetween(String value1, String value2) {
            addCriterion("punish_id between", value1, value2, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishIdNotBetween(String value1, String value2) {
            addCriterion("punish_id not between", value1, value2, "punishId");
            return (Criteria) this;
        }

        public Criteria andPunishResultIsNull() {
            addCriterion("punish_result is null");
            return (Criteria) this;
        }

        public Criteria andPunishResultIsNotNull() {
            addCriterion("punish_result is not null");
            return (Criteria) this;
        }

        public Criteria andPunishResultEqualTo(String value) {
            addCriterion("punish_result =", value, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultNotEqualTo(String value) {
            addCriterion("punish_result <>", value, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultGreaterThan(String value) {
            addCriterion("punish_result >", value, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultGreaterThanOrEqualTo(String value) {
            addCriterion("punish_result >=", value, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultLessThan(String value) {
            addCriterion("punish_result <", value, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultLessThanOrEqualTo(String value) {
            addCriterion("punish_result <=", value, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultLike(String value) {
            addCriterion("punish_result like", value, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultNotLike(String value) {
            addCriterion("punish_result not like", value, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultIn(List<String> values) {
            addCriterion("punish_result in", values, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultNotIn(List<String> values) {
            addCriterion("punish_result not in", values, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultBetween(String value1, String value2) {
            addCriterion("punish_result between", value1, value2, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishResultNotBetween(String value1, String value2) {
            addCriterion("punish_result not between", value1, value2, "punishResult");
            return (Criteria) this;
        }

        public Criteria andPunishTimeIsNull() {
            addCriterion("punish_time is null");
            return (Criteria) this;
        }

        public Criteria andPunishTimeIsNotNull() {
            addCriterion("punish_time is not null");
            return (Criteria) this;
        }

        public Criteria andPunishTimeEqualTo(String value) {
            addCriterion("punish_time =", value, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeNotEqualTo(String value) {
            addCriterion("punish_time <>", value, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeGreaterThan(String value) {
            addCriterion("punish_time >", value, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeGreaterThanOrEqualTo(String value) {
            addCriterion("punish_time >=", value, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeLessThan(String value) {
            addCriterion("punish_time <", value, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeLessThanOrEqualTo(String value) {
            addCriterion("punish_time <=", value, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeLike(String value) {
            addCriterion("punish_time like", value, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeNotLike(String value) {
            addCriterion("punish_time not like", value, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeIn(List<String> values) {
            addCriterion("punish_time in", values, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeNotIn(List<String> values) {
            addCriterion("punish_time not in", values, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeBetween(String value1, String value2) {
            addCriterion("punish_time between", value1, value2, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishTimeNotBetween(String value1, String value2) {
            addCriterion("punish_time not between", value1, value2, "punishTime");
            return (Criteria) this;
        }

        public Criteria andPunishScoreIsNull() {
            addCriterion("punish_score is null");
            return (Criteria) this;
        }

        public Criteria andPunishScoreIsNotNull() {
            addCriterion("punish_score is not null");
            return (Criteria) this;
        }

        public Criteria andPunishScoreEqualTo(Integer value) {
            addCriterion("punish_score =", value, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreNotEqualTo(Integer value) {
            addCriterion("punish_score <>", value, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreGreaterThan(Integer value) {
            addCriterion("punish_score >", value, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("punish_score >=", value, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreLessThan(Integer value) {
            addCriterion("punish_score <", value, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreLessThanOrEqualTo(Integer value) {
            addCriterion("punish_score <=", value, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreIn(List<Integer> values) {
            addCriterion("punish_score in", values, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreNotIn(List<Integer> values) {
            addCriterion("punish_score not in", values, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreBetween(Integer value1, Integer value2) {
            addCriterion("punish_score between", value1, value2, "punishScore");
            return (Criteria) this;
        }

        public Criteria andPunishScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("punish_score not between", value1, value2, "punishScore");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_punish
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_punish
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}