package com.sd.Admin.pojo;

public class sd_punish {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_punish.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_punish.punish_id
     *
     * @mbg.generated
     */
    private String punishId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_punish.punish_result
     *
     * @mbg.generated
     */
    private String punishResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_punish.punish_time
     *
     * @mbg.generated
     */
    private String punishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_punish.punish_score
     *
     * @mbg.generated
     */
    private Integer punishScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_punish.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_punish.Id
     *
     * @return the value of sd_punish.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_punish.Id
     *
     * @param id the value for sd_punish.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_punish.punish_id
     *
     * @return the value of sd_punish.punish_id
     *
     * @mbg.generated
     */
    public String getPunishId() {
        return punishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_punish.punish_id
     *
     * @param punishId the value for sd_punish.punish_id
     *
     * @mbg.generated
     */
    public void setPunishId(String punishId) {
        this.punishId = punishId == null ? null : punishId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_punish.punish_result
     *
     * @return the value of sd_punish.punish_result
     *
     * @mbg.generated
     */
    public String getPunishResult() {
        return punishResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_punish.punish_result
     *
     * @param punishResult the value for sd_punish.punish_result
     *
     * @mbg.generated
     */
    public void setPunishResult(String punishResult) {
        this.punishResult = punishResult == null ? null : punishResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_punish.punish_time
     *
     * @return the value of sd_punish.punish_time
     *
     * @mbg.generated
     */
    public String getPunishTime() {
        return punishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_punish.punish_time
     *
     * @param punishTime the value for sd_punish.punish_time
     *
     * @mbg.generated
     */
    public void setPunishTime(String punishTime) {
        this.punishTime = punishTime == null ? null : punishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_punish.punish_score
     *
     * @return the value of sd_punish.punish_score
     *
     * @mbg.generated
     */
    public Integer getPunishScore() {
        return punishScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_punish.punish_score
     *
     * @param punishScore the value for sd_punish.punish_score
     *
     * @mbg.generated
     */
    public void setPunishScore(Integer punishScore) {
        this.punishScore = punishScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_punish.student_id
     *
     * @return the value of sd_punish.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_punish.student_id
     *
     * @param studentId the value for sd_punish.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }
}