package com.sd.Admin.pojo;

public class sd_reward {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_reward.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_reward.reward_id
     *
     * @mbg.generated
     */
    private String rewardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_reward.reward_result
     *
     * @mbg.generated
     */
    private String rewardResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_reward.reward_time
     *
     * @mbg.generated
     */
    private String rewardTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_reward.reward_score
     *
     * @mbg.generated
     */
    private Integer rewardScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_reward.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_reward.Id
     *
     * @return the value of sd_reward.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_reward.Id
     *
     * @param id the value for sd_reward.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_reward.reward_id
     *
     * @return the value of sd_reward.reward_id
     *
     * @mbg.generated
     */
    public String getRewardId() {
        return rewardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_reward.reward_id
     *
     * @param rewardId the value for sd_reward.reward_id
     *
     * @mbg.generated
     */
    public void setRewardId(String rewardId) {
        this.rewardId = rewardId == null ? null : rewardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_reward.reward_result
     *
     * @return the value of sd_reward.reward_result
     *
     * @mbg.generated
     */
    public String getRewardResult() {
        return rewardResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_reward.reward_result
     *
     * @param rewardResult the value for sd_reward.reward_result
     *
     * @mbg.generated
     */
    public void setRewardResult(String rewardResult) {
        this.rewardResult = rewardResult == null ? null : rewardResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_reward.reward_time
     *
     * @return the value of sd_reward.reward_time
     *
     * @mbg.generated
     */
    public String getRewardTime() {
        return rewardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_reward.reward_time
     *
     * @param rewardTime the value for sd_reward.reward_time
     *
     * @mbg.generated
     */
    public void setRewardTime(String rewardTime) {
        this.rewardTime = rewardTime == null ? null : rewardTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_reward.reward_score
     *
     * @return the value of sd_reward.reward_score
     *
     * @mbg.generated
     */
    public Integer getRewardScore() {
        return rewardScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_reward.reward_score
     *
     * @param rewardScore the value for sd_reward.reward_score
     *
     * @mbg.generated
     */
    public void setRewardScore(Integer rewardScore) {
        this.rewardScore = rewardScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_reward.student_id
     *
     * @return the value of sd_reward.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_reward.student_id
     *
     * @param studentId the value for sd_reward.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }
}