package com.sd.Admin.pojo;

import java.util.ArrayList;
import java.util.List;

public class sd_rewardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public sd_rewardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRewardIdIsNull() {
            addCriterion("reward_id is null");
            return (Criteria) this;
        }

        public Criteria andRewardIdIsNotNull() {
            addCriterion("reward_id is not null");
            return (Criteria) this;
        }

        public Criteria andRewardIdEqualTo(String value) {
            addCriterion("reward_id =", value, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdNotEqualTo(String value) {
            addCriterion("reward_id <>", value, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdGreaterThan(String value) {
            addCriterion("reward_id >", value, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdGreaterThanOrEqualTo(String value) {
            addCriterion("reward_id >=", value, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdLessThan(String value) {
            addCriterion("reward_id <", value, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdLessThanOrEqualTo(String value) {
            addCriterion("reward_id <=", value, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdLike(String value) {
            addCriterion("reward_id like", value, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdNotLike(String value) {
            addCriterion("reward_id not like", value, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdIn(List<String> values) {
            addCriterion("reward_id in", values, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdNotIn(List<String> values) {
            addCriterion("reward_id not in", values, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdBetween(String value1, String value2) {
            addCriterion("reward_id between", value1, value2, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardIdNotBetween(String value1, String value2) {
            addCriterion("reward_id not between", value1, value2, "rewardId");
            return (Criteria) this;
        }

        public Criteria andRewardResultIsNull() {
            addCriterion("reward_result is null");
            return (Criteria) this;
        }

        public Criteria andRewardResultIsNotNull() {
            addCriterion("reward_result is not null");
            return (Criteria) this;
        }

        public Criteria andRewardResultEqualTo(String value) {
            addCriterion("reward_result =", value, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultNotEqualTo(String value) {
            addCriterion("reward_result <>", value, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultGreaterThan(String value) {
            addCriterion("reward_result >", value, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultGreaterThanOrEqualTo(String value) {
            addCriterion("reward_result >=", value, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultLessThan(String value) {
            addCriterion("reward_result <", value, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultLessThanOrEqualTo(String value) {
            addCriterion("reward_result <=", value, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultLike(String value) {
            addCriterion("reward_result like", value, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultNotLike(String value) {
            addCriterion("reward_result not like", value, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultIn(List<String> values) {
            addCriterion("reward_result in", values, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultNotIn(List<String> values) {
            addCriterion("reward_result not in", values, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultBetween(String value1, String value2) {
            addCriterion("reward_result between", value1, value2, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardResultNotBetween(String value1, String value2) {
            addCriterion("reward_result not between", value1, value2, "rewardResult");
            return (Criteria) this;
        }

        public Criteria andRewardTimeIsNull() {
            addCriterion("reward_time is null");
            return (Criteria) this;
        }

        public Criteria andRewardTimeIsNotNull() {
            addCriterion("reward_time is not null");
            return (Criteria) this;
        }

        public Criteria andRewardTimeEqualTo(String value) {
            addCriterion("reward_time =", value, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeNotEqualTo(String value) {
            addCriterion("reward_time <>", value, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeGreaterThan(String value) {
            addCriterion("reward_time >", value, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeGreaterThanOrEqualTo(String value) {
            addCriterion("reward_time >=", value, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeLessThan(String value) {
            addCriterion("reward_time <", value, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeLessThanOrEqualTo(String value) {
            addCriterion("reward_time <=", value, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeLike(String value) {
            addCriterion("reward_time like", value, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeNotLike(String value) {
            addCriterion("reward_time not like", value, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeIn(List<String> values) {
            addCriterion("reward_time in", values, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeNotIn(List<String> values) {
            addCriterion("reward_time not in", values, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeBetween(String value1, String value2) {
            addCriterion("reward_time between", value1, value2, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardTimeNotBetween(String value1, String value2) {
            addCriterion("reward_time not between", value1, value2, "rewardTime");
            return (Criteria) this;
        }

        public Criteria andRewardScoreIsNull() {
            addCriterion("reward_score is null");
            return (Criteria) this;
        }

        public Criteria andRewardScoreIsNotNull() {
            addCriterion("reward_score is not null");
            return (Criteria) this;
        }

        public Criteria andRewardScoreEqualTo(Integer value) {
            addCriterion("reward_score =", value, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreNotEqualTo(Integer value) {
            addCriterion("reward_score <>", value, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreGreaterThan(Integer value) {
            addCriterion("reward_score >", value, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("reward_score >=", value, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreLessThan(Integer value) {
            addCriterion("reward_score <", value, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreLessThanOrEqualTo(Integer value) {
            addCriterion("reward_score <=", value, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreIn(List<Integer> values) {
            addCriterion("reward_score in", values, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreNotIn(List<Integer> values) {
            addCriterion("reward_score not in", values, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreBetween(Integer value1, Integer value2) {
            addCriterion("reward_score between", value1, value2, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andRewardScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("reward_score not between", value1, value2, "rewardScore");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_reward
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_reward
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}