package com.sd.Admin.pojo;

public class sd_student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_name
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_phone
     *
     * @mbg.generated
     */
    private String studentPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_idcard
     *
     * @mbg.generated
     */
    private String studentIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_issign
     *
     * @mbg.generated
     */
    private Integer studentIssign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_signtime
     *
     * @mbg.generated
     */
    private String studentSigntime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_pictrue
     *
     * @mbg.generated
     */
    private String studentPictrue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_kpl
     *
     * @mbg.generated
     */
    private Integer studentKpl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_vocate
     *
     * @mbg.generated
     */
    private Integer studentVocate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_class
     *
     * @mbg.generated
     */
    private String studentClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_major
     *
     * @mbg.generated
     */
    private String studentMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_student.student_grade
     *
     * @mbg.generated
     */
    private String studentGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.Id
     *
     * @return the value of sd_student.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.Id
     *
     * @param id the value for sd_student.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_id
     *
     * @return the value of sd_student.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_id
     *
     * @param studentId the value for sd_student.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_name
     *
     * @return the value of sd_student.student_name
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_name
     *
     * @param studentName the value for sd_student.student_name
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_phone
     *
     * @return the value of sd_student.student_phone
     *
     * @mbg.generated
     */
    public String getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_phone
     *
     * @param studentPhone the value for sd_student.student_phone
     *
     * @mbg.generated
     */
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone == null ? null : studentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_idcard
     *
     * @return the value of sd_student.student_idcard
     *
     * @mbg.generated
     */
    public String getStudentIdcard() {
        return studentIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_idcard
     *
     * @param studentIdcard the value for sd_student.student_idcard
     *
     * @mbg.generated
     */
    public void setStudentIdcard(String studentIdcard) {
        this.studentIdcard = studentIdcard == null ? null : studentIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_issign
     *
     * @return the value of sd_student.student_issign
     *
     * @mbg.generated
     */
    public Integer getStudentIssign() {
        return studentIssign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_issign
     *
     * @param studentIssign the value for sd_student.student_issign
     *
     * @mbg.generated
     */
    public void setStudentIssign(Integer studentIssign) {
        this.studentIssign = studentIssign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_signtime
     *
     * @return the value of sd_student.student_signtime
     *
     * @mbg.generated
     */
    public String getStudentSigntime() {
        return studentSigntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_signtime
     *
     * @param studentSigntime the value for sd_student.student_signtime
     *
     * @mbg.generated
     */
    public void setStudentSigntime(String studentSigntime) {
        this.studentSigntime = studentSigntime == null ? null : studentSigntime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_pictrue
     *
     * @return the value of sd_student.student_pictrue
     *
     * @mbg.generated
     */
    public String getStudentPictrue() {
        return studentPictrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_pictrue
     *
     * @param studentPictrue the value for sd_student.student_pictrue
     *
     * @mbg.generated
     */
    public void setStudentPictrue(String studentPictrue) {
        this.studentPictrue = studentPictrue == null ? null : studentPictrue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_kpl
     *
     * @return the value of sd_student.student_kpl
     *
     * @mbg.generated
     */
    public Integer getStudentKpl() {
        return studentKpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_kpl
     *
     * @param studentKpl the value for sd_student.student_kpl
     *
     * @mbg.generated
     */
    public void setStudentKpl(Integer studentKpl) {
        this.studentKpl = studentKpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_vocate
     *
     * @return the value of sd_student.student_vocate
     *
     * @mbg.generated
     */
    public Integer getStudentVocate() {
        return studentVocate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_vocate
     *
     * @param studentVocate the value for sd_student.student_vocate
     *
     * @mbg.generated
     */
    public void setStudentVocate(Integer studentVocate) {
        this.studentVocate = studentVocate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.user_id
     *
     * @return the value of sd_student.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.user_id
     *
     * @param userId the value for sd_student.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_class
     *
     * @return the value of sd_student.student_class
     *
     * @mbg.generated
     */
    public String getStudentClass() {
        return studentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_class
     *
     * @param studentClass the value for sd_student.student_class
     *
     * @mbg.generated
     */
    public void setStudentClass(String studentClass) {
        this.studentClass = studentClass == null ? null : studentClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_major
     *
     * @return the value of sd_student.student_major
     *
     * @mbg.generated
     */
    public String getStudentMajor() {
        return studentMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_major
     *
     * @param studentMajor the value for sd_student.student_major
     *
     * @mbg.generated
     */
    public void setStudentMajor(String studentMajor) {
        this.studentMajor = studentMajor == null ? null : studentMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_student.student_grade
     *
     * @return the value of sd_student.student_grade
     *
     * @mbg.generated
     */
    public String getStudentGrade() {
        return studentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_student.student_grade
     *
     * @param studentGrade the value for sd_student.student_grade
     *
     * @mbg.generated
     */
    public void setStudentGrade(String studentGrade) {
        this.studentGrade = studentGrade == null ? null : studentGrade.trim();
    }
}