package com.sd.Admin.pojo;

import java.util.ArrayList;
import java.util.List;

public class sd_studentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public sd_studentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNull() {
            addCriterion("student_phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNotNull() {
            addCriterion("student_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneEqualTo(String value) {
            addCriterion("student_phone =", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotEqualTo(String value) {
            addCriterion("student_phone <>", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThan(String value) {
            addCriterion("student_phone >", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("student_phone >=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThan(String value) {
            addCriterion("student_phone <", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThanOrEqualTo(String value) {
            addCriterion("student_phone <=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLike(String value) {
            addCriterion("student_phone like", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotLike(String value) {
            addCriterion("student_phone not like", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIn(List<String> values) {
            addCriterion("student_phone in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotIn(List<String> values) {
            addCriterion("student_phone not in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneBetween(String value1, String value2) {
            addCriterion("student_phone between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotBetween(String value1, String value2) {
            addCriterion("student_phone not between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardIsNull() {
            addCriterion("student_idcard is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardIsNotNull() {
            addCriterion("student_idcard is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardEqualTo(String value) {
            addCriterion("student_idcard =", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardNotEqualTo(String value) {
            addCriterion("student_idcard <>", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardGreaterThan(String value) {
            addCriterion("student_idcard >", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("student_idcard >=", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardLessThan(String value) {
            addCriterion("student_idcard <", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardLessThanOrEqualTo(String value) {
            addCriterion("student_idcard <=", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardLike(String value) {
            addCriterion("student_idcard like", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardNotLike(String value) {
            addCriterion("student_idcard not like", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardIn(List<String> values) {
            addCriterion("student_idcard in", values, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardNotIn(List<String> values) {
            addCriterion("student_idcard not in", values, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardBetween(String value1, String value2) {
            addCriterion("student_idcard between", value1, value2, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardNotBetween(String value1, String value2) {
            addCriterion("student_idcard not between", value1, value2, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIssignIsNull() {
            addCriterion("student_issign is null");
            return (Criteria) this;
        }

        public Criteria andStudentIssignIsNotNull() {
            addCriterion("student_issign is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIssignEqualTo(Integer value) {
            addCriterion("student_issign =", value, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignNotEqualTo(Integer value) {
            addCriterion("student_issign <>", value, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignGreaterThan(Integer value) {
            addCriterion("student_issign >", value, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_issign >=", value, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignLessThan(Integer value) {
            addCriterion("student_issign <", value, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignLessThanOrEqualTo(Integer value) {
            addCriterion("student_issign <=", value, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignIn(List<Integer> values) {
            addCriterion("student_issign in", values, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignNotIn(List<Integer> values) {
            addCriterion("student_issign not in", values, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignBetween(Integer value1, Integer value2) {
            addCriterion("student_issign between", value1, value2, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentIssignNotBetween(Integer value1, Integer value2) {
            addCriterion("student_issign not between", value1, value2, "studentIssign");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeIsNull() {
            addCriterion("student_signtime is null");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeIsNotNull() {
            addCriterion("student_signtime is not null");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeEqualTo(String value) {
            addCriterion("student_signtime =", value, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeNotEqualTo(String value) {
            addCriterion("student_signtime <>", value, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeGreaterThan(String value) {
            addCriterion("student_signtime >", value, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeGreaterThanOrEqualTo(String value) {
            addCriterion("student_signtime >=", value, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeLessThan(String value) {
            addCriterion("student_signtime <", value, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeLessThanOrEqualTo(String value) {
            addCriterion("student_signtime <=", value, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeLike(String value) {
            addCriterion("student_signtime like", value, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeNotLike(String value) {
            addCriterion("student_signtime not like", value, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeIn(List<String> values) {
            addCriterion("student_signtime in", values, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeNotIn(List<String> values) {
            addCriterion("student_signtime not in", values, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeBetween(String value1, String value2) {
            addCriterion("student_signtime between", value1, value2, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentSigntimeNotBetween(String value1, String value2) {
            addCriterion("student_signtime not between", value1, value2, "studentSigntime");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueIsNull() {
            addCriterion("student_pictrue is null");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueIsNotNull() {
            addCriterion("student_pictrue is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueEqualTo(String value) {
            addCriterion("student_pictrue =", value, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueNotEqualTo(String value) {
            addCriterion("student_pictrue <>", value, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueGreaterThan(String value) {
            addCriterion("student_pictrue >", value, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueGreaterThanOrEqualTo(String value) {
            addCriterion("student_pictrue >=", value, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueLessThan(String value) {
            addCriterion("student_pictrue <", value, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueLessThanOrEqualTo(String value) {
            addCriterion("student_pictrue <=", value, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueLike(String value) {
            addCriterion("student_pictrue like", value, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueNotLike(String value) {
            addCriterion("student_pictrue not like", value, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueIn(List<String> values) {
            addCriterion("student_pictrue in", values, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueNotIn(List<String> values) {
            addCriterion("student_pictrue not in", values, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueBetween(String value1, String value2) {
            addCriterion("student_pictrue between", value1, value2, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentPictrueNotBetween(String value1, String value2) {
            addCriterion("student_pictrue not between", value1, value2, "studentPictrue");
            return (Criteria) this;
        }

        public Criteria andStudentKplIsNull() {
            addCriterion("student_kpl is null");
            return (Criteria) this;
        }

        public Criteria andStudentKplIsNotNull() {
            addCriterion("student_kpl is not null");
            return (Criteria) this;
        }

        public Criteria andStudentKplEqualTo(Integer value) {
            addCriterion("student_kpl =", value, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplNotEqualTo(Integer value) {
            addCriterion("student_kpl <>", value, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplGreaterThan(Integer value) {
            addCriterion("student_kpl >", value, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_kpl >=", value, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplLessThan(Integer value) {
            addCriterion("student_kpl <", value, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplLessThanOrEqualTo(Integer value) {
            addCriterion("student_kpl <=", value, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplIn(List<Integer> values) {
            addCriterion("student_kpl in", values, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplNotIn(List<Integer> values) {
            addCriterion("student_kpl not in", values, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplBetween(Integer value1, Integer value2) {
            addCriterion("student_kpl between", value1, value2, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentKplNotBetween(Integer value1, Integer value2) {
            addCriterion("student_kpl not between", value1, value2, "studentKpl");
            return (Criteria) this;
        }

        public Criteria andStudentVocateIsNull() {
            addCriterion("student_vocate is null");
            return (Criteria) this;
        }

        public Criteria andStudentVocateIsNotNull() {
            addCriterion("student_vocate is not null");
            return (Criteria) this;
        }

        public Criteria andStudentVocateEqualTo(Integer value) {
            addCriterion("student_vocate =", value, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateNotEqualTo(Integer value) {
            addCriterion("student_vocate <>", value, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateGreaterThan(Integer value) {
            addCriterion("student_vocate >", value, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_vocate >=", value, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateLessThan(Integer value) {
            addCriterion("student_vocate <", value, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateLessThanOrEqualTo(Integer value) {
            addCriterion("student_vocate <=", value, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateIn(List<Integer> values) {
            addCriterion("student_vocate in", values, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateNotIn(List<Integer> values) {
            addCriterion("student_vocate not in", values, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateBetween(Integer value1, Integer value2) {
            addCriterion("student_vocate between", value1, value2, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andStudentVocateNotBetween(Integer value1, Integer value2) {
            addCriterion("student_vocate not between", value1, value2, "studentVocate");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStudentClassIsNull() {
            addCriterion("student_class is null");
            return (Criteria) this;
        }

        public Criteria andStudentClassIsNotNull() {
            addCriterion("student_class is not null");
            return (Criteria) this;
        }

        public Criteria andStudentClassEqualTo(String value) {
            addCriterion("student_class =", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotEqualTo(String value) {
            addCriterion("student_class <>", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassGreaterThan(String value) {
            addCriterion("student_class >", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassGreaterThanOrEqualTo(String value) {
            addCriterion("student_class >=", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLessThan(String value) {
            addCriterion("student_class <", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLessThanOrEqualTo(String value) {
            addCriterion("student_class <=", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLike(String value) {
            addCriterion("student_class like", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotLike(String value) {
            addCriterion("student_class not like", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassIn(List<String> values) {
            addCriterion("student_class in", values, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotIn(List<String> values) {
            addCriterion("student_class not in", values, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassBetween(String value1, String value2) {
            addCriterion("student_class between", value1, value2, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotBetween(String value1, String value2) {
            addCriterion("student_class not between", value1, value2, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIsNull() {
            addCriterion("student_major is null");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIsNotNull() {
            addCriterion("student_major is not null");
            return (Criteria) this;
        }

        public Criteria andStudentMajorEqualTo(String value) {
            addCriterion("student_major =", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotEqualTo(String value) {
            addCriterion("student_major <>", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorGreaterThan(String value) {
            addCriterion("student_major >", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorGreaterThanOrEqualTo(String value) {
            addCriterion("student_major >=", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLessThan(String value) {
            addCriterion("student_major <", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLessThanOrEqualTo(String value) {
            addCriterion("student_major <=", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLike(String value) {
            addCriterion("student_major like", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotLike(String value) {
            addCriterion("student_major not like", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIn(List<String> values) {
            addCriterion("student_major in", values, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotIn(List<String> values) {
            addCriterion("student_major not in", values, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorBetween(String value1, String value2) {
            addCriterion("student_major between", value1, value2, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotBetween(String value1, String value2) {
            addCriterion("student_major not between", value1, value2, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentGradeIsNull() {
            addCriterion("student_grade is null");
            return (Criteria) this;
        }

        public Criteria andStudentGradeIsNotNull() {
            addCriterion("student_grade is not null");
            return (Criteria) this;
        }

        public Criteria andStudentGradeEqualTo(String value) {
            addCriterion("student_grade =", value, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeNotEqualTo(String value) {
            addCriterion("student_grade <>", value, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeGreaterThan(String value) {
            addCriterion("student_grade >", value, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeGreaterThanOrEqualTo(String value) {
            addCriterion("student_grade >=", value, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeLessThan(String value) {
            addCriterion("student_grade <", value, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeLessThanOrEqualTo(String value) {
            addCriterion("student_grade <=", value, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeLike(String value) {
            addCriterion("student_grade like", value, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeNotLike(String value) {
            addCriterion("student_grade not like", value, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeIn(List<String> values) {
            addCriterion("student_grade in", values, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeNotIn(List<String> values) {
            addCriterion("student_grade not in", values, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeBetween(String value1, String value2) {
            addCriterion("student_grade between", value1, value2, "studentGrade");
            return (Criteria) this;
        }

        public Criteria andStudentGradeNotBetween(String value1, String value2) {
            addCriterion("student_grade not between", value1, value2, "studentGrade");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_student
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}