package com.sd.Admin.pojo;

public class sd_user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_user.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_user.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_user.user_nickname
     *
     * @mbg.generated
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_user.user_pictrue
     *
     * @mbg.generated
     */
    private String userPictrue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_user.user_permission
     *
     * @mbg.generated
     */
    private Integer userPermission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_user.user_issign
     *
     * @mbg.generated
     */
    private Integer userIssign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_user.user_signtime
     *
     * @mbg.generated
     */
    private String userSigntime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_user.Id
     *
     * @return the value of sd_user.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_user.Id
     *
     * @param id the value for sd_user.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_user.user_id
     *
     * @return the value of sd_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_user.user_id
     *
     * @param userId the value for sd_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_user.user_password
     *
     * @return the value of sd_user.user_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_user.user_password
     *
     * @param userPassword the value for sd_user.user_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_user.user_nickname
     *
     * @return the value of sd_user.user_nickname
     *
     * @mbg.generated
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_user.user_nickname
     *
     * @param userNickname the value for sd_user.user_nickname
     *
     * @mbg.generated
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_user.user_pictrue
     *
     * @return the value of sd_user.user_pictrue
     *
     * @mbg.generated
     */
    public String getUserPictrue() {
        return userPictrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_user.user_pictrue
     *
     * @param userPictrue the value for sd_user.user_pictrue
     *
     * @mbg.generated
     */
    public void setUserPictrue(String userPictrue) {
        this.userPictrue = userPictrue == null ? null : userPictrue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_user.user_permission
     *
     * @return the value of sd_user.user_permission
     *
     * @mbg.generated
     */
    public Integer getUserPermission() {
        return userPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_user.user_permission
     *
     * @param userPermission the value for sd_user.user_permission
     *
     * @mbg.generated
     */
    public void setUserPermission(Integer userPermission) {
        this.userPermission = userPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_user.user_issign
     *
     * @return the value of sd_user.user_issign
     *
     * @mbg.generated
     */
    public Integer getUserIssign() {
        return userIssign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_user.user_issign
     *
     * @param userIssign the value for sd_user.user_issign
     *
     * @mbg.generated
     */
    public void setUserIssign(Integer userIssign) {
        this.userIssign = userIssign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_user.user_signtime
     *
     * @return the value of sd_user.user_signtime
     *
     * @mbg.generated
     */
    public String getUserSigntime() {
        return userSigntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_user.user_signtime
     *
     * @param userSigntime the value for sd_user.user_signtime
     *
     * @mbg.generated
     */
    public void setUserSigntime(String userSigntime) {
        this.userSigntime = userSigntime == null ? null : userSigntime.trim();
    }
}