package com.sd.Admin.pojo;

import java.util.ArrayList;
import java.util.List;

public class sd_userExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public sd_userExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("user_password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("user_password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("user_password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("user_password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("user_password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("user_password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("user_password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("user_password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("user_password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("user_password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("user_password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("user_password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("user_password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("user_password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserNicknameIsNull() {
            addCriterion("user_nickname is null");
            return (Criteria) this;
        }

        public Criteria andUserNicknameIsNotNull() {
            addCriterion("user_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andUserNicknameEqualTo(String value) {
            addCriterion("user_nickname =", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameNotEqualTo(String value) {
            addCriterion("user_nickname <>", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameGreaterThan(String value) {
            addCriterion("user_nickname >", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("user_nickname >=", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameLessThan(String value) {
            addCriterion("user_nickname <", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameLessThanOrEqualTo(String value) {
            addCriterion("user_nickname <=", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameLike(String value) {
            addCriterion("user_nickname like", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameNotLike(String value) {
            addCriterion("user_nickname not like", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameIn(List<String> values) {
            addCriterion("user_nickname in", values, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameNotIn(List<String> values) {
            addCriterion("user_nickname not in", values, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameBetween(String value1, String value2) {
            addCriterion("user_nickname between", value1, value2, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameNotBetween(String value1, String value2) {
            addCriterion("user_nickname not between", value1, value2, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserPictrueIsNull() {
            addCriterion("user_pictrue is null");
            return (Criteria) this;
        }

        public Criteria andUserPictrueIsNotNull() {
            addCriterion("user_pictrue is not null");
            return (Criteria) this;
        }

        public Criteria andUserPictrueEqualTo(String value) {
            addCriterion("user_pictrue =", value, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueNotEqualTo(String value) {
            addCriterion("user_pictrue <>", value, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueGreaterThan(String value) {
            addCriterion("user_pictrue >", value, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueGreaterThanOrEqualTo(String value) {
            addCriterion("user_pictrue >=", value, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueLessThan(String value) {
            addCriterion("user_pictrue <", value, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueLessThanOrEqualTo(String value) {
            addCriterion("user_pictrue <=", value, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueLike(String value) {
            addCriterion("user_pictrue like", value, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueNotLike(String value) {
            addCriterion("user_pictrue not like", value, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueIn(List<String> values) {
            addCriterion("user_pictrue in", values, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueNotIn(List<String> values) {
            addCriterion("user_pictrue not in", values, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueBetween(String value1, String value2) {
            addCriterion("user_pictrue between", value1, value2, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPictrueNotBetween(String value1, String value2) {
            addCriterion("user_pictrue not between", value1, value2, "userPictrue");
            return (Criteria) this;
        }

        public Criteria andUserPermissionIsNull() {
            addCriterion("user_permission is null");
            return (Criteria) this;
        }

        public Criteria andUserPermissionIsNotNull() {
            addCriterion("user_permission is not null");
            return (Criteria) this;
        }

        public Criteria andUserPermissionEqualTo(Integer value) {
            addCriterion("user_permission =", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionNotEqualTo(Integer value) {
            addCriterion("user_permission <>", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionGreaterThan(Integer value) {
            addCriterion("user_permission >", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_permission >=", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionLessThan(Integer value) {
            addCriterion("user_permission <", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionLessThanOrEqualTo(Integer value) {
            addCriterion("user_permission <=", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionIn(List<Integer> values) {
            addCriterion("user_permission in", values, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionNotIn(List<Integer> values) {
            addCriterion("user_permission not in", values, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionBetween(Integer value1, Integer value2) {
            addCriterion("user_permission between", value1, value2, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionNotBetween(Integer value1, Integer value2) {
            addCriterion("user_permission not between", value1, value2, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserIssignIsNull() {
            addCriterion("user_issign is null");
            return (Criteria) this;
        }

        public Criteria andUserIssignIsNotNull() {
            addCriterion("user_issign is not null");
            return (Criteria) this;
        }

        public Criteria andUserIssignEqualTo(Integer value) {
            addCriterion("user_issign =", value, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignNotEqualTo(Integer value) {
            addCriterion("user_issign <>", value, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignGreaterThan(Integer value) {
            addCriterion("user_issign >", value, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_issign >=", value, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignLessThan(Integer value) {
            addCriterion("user_issign <", value, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignLessThanOrEqualTo(Integer value) {
            addCriterion("user_issign <=", value, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignIn(List<Integer> values) {
            addCriterion("user_issign in", values, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignNotIn(List<Integer> values) {
            addCriterion("user_issign not in", values, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignBetween(Integer value1, Integer value2) {
            addCriterion("user_issign between", value1, value2, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserIssignNotBetween(Integer value1, Integer value2) {
            addCriterion("user_issign not between", value1, value2, "userIssign");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeIsNull() {
            addCriterion("user_signtime is null");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeIsNotNull() {
            addCriterion("user_signtime is not null");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeEqualTo(String value) {
            addCriterion("user_signtime =", value, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeNotEqualTo(String value) {
            addCriterion("user_signtime <>", value, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeGreaterThan(String value) {
            addCriterion("user_signtime >", value, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeGreaterThanOrEqualTo(String value) {
            addCriterion("user_signtime >=", value, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeLessThan(String value) {
            addCriterion("user_signtime <", value, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeLessThanOrEqualTo(String value) {
            addCriterion("user_signtime <=", value, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeLike(String value) {
            addCriterion("user_signtime like", value, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeNotLike(String value) {
            addCriterion("user_signtime not like", value, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeIn(List<String> values) {
            addCriterion("user_signtime in", values, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeNotIn(List<String> values) {
            addCriterion("user_signtime not in", values, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeBetween(String value1, String value2) {
            addCriterion("user_signtime between", value1, value2, "userSigntime");
            return (Criteria) this;
        }

        public Criteria andUserSigntimeNotBetween(String value1, String value2) {
            addCriterion("user_signtime not between", value1, value2, "userSigntime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}