package com.sd.Admin.mapper;

import java.util.List;
import com.sd.Admin.pojo.sd_activity;
import com.sd.Admin.pojo.sd_activityExample;

public interface sd_activityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_activity
     *
     * @mbg.generated
     */
    int insert(sd_activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_activity
     *
     * @mbg.generated
     */
    int insertSelective(sd_activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_activity
     *
     * @mbg.generated
     */
    List<sd_activity> selectByExample(sd_activityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_activity
     *
     * @mbg.generated
     */
    sd_activity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(sd_activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(sd_activity record);
    
    List<sd_activity> getActivityList();
}