package com.sd.Admin.mapper;

import java.util.List;
import com.sd.Admin.pojo.sd_class;
import com.sd.Admin.pojo.sd_classExample;

public interface sd_classMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_class
     *
     * @mbg.generated
     */
    int insert(sd_class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_class
     *
     * @mbg.generated
     */
    int insertSelective(sd_class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_class
     *
     * @mbg.generated
     */
    List<sd_class> selectByExample(sd_classExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_class
     *
     * @mbg.generated
     */
    sd_class selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(sd_class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(sd_class record);
}