package com.sd.Admin.mapper;

import java.util.List;
import com.sd.Admin.pojo.sd_check;
import com.sd.Admin.pojo.sd_checkExample;

public interface sd_checkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    int insert(sd_check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    int insertSelective(sd_check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    List<sd_check> selectByExample(sd_checkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    sd_check selectByPrimaryKey(String todayTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(sd_check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(sd_check record);
    
    List<sd_check> getCheckList();
}