package com.sd.Admin.mapper;

import java.util.List;
import com.sd.Admin.pojo.sd_student;
import com.sd.Admin.pojo.sd_studentExample;

public interface sd_studentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    int insert(sd_student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    int insertSelective(sd_student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    List<sd_student> selectByExample(sd_studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    sd_student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(sd_student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(sd_student record);
    
    //返回查找的学生列表
    List<sd_student> getStudents(String studentClass,String studentMajor,String studentGrade);
    //返回所有的学生
	List<sd_student> getStudentsList();
}